import { useState } from "react";

import FormField from "../components/FormField";
import Loader from "../components/Loader";
import Card from '../components/Card';

interface CardDataProps {
  data: string[];
  statusMsg: string;
}

const RenderCards = ({data, statusMsg}: CardDataProps) => {
  if (data.length > 0) {
    return (
      data.map((post) => <Card key={post} imgData={post} />)
    )
  } else {
    return (
      <h2>{statusMsg}</h2>
    )
  }
}

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("abc");

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-slate-700 text-xl">
          The Community showcase
        </h1>
        <p className="mt-2 text-slate-400">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>

      <div className="mt-16">
        <FormField />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <div>
            {searchText && (
              <div className="text-slate-400 font-medium text-xl mb-3">
                Showing results for <span className="text-slate-700">{searchText}</span>
              </div>
              )}
              <div className="grid grid-cols-1 xs:grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
                {searchText ? (
                  <RenderCards data={[]} statusMsg="No search results found" />
                ) : (
                    <RenderCards data={[]} statusMsg="No posts found" />
                )}
              </div>
          </div>
        )}
      </div>
    </section>
  );
};

export default Home;
